Add missing includes
Without the gpio header you get these errors outside of the Arduino environment:
```
 error: 'GPIO_PIN_MUX_REG' undeclared (first use in this function)
```